---
title: "Methods for Handling Multiple Outcomes in Health Data"
subtitle: 'PCA Clinical Annotation'
author: "Sivakamakshi Muthu Kumarasamy, Shivadarshini Sreekanth"
output: 
  rmdformats::readthedown:
    self_contained: true
    highlight: "default"
    thumbnails: false
    fig_width: 7
    fig_height: 5
    toc_depth: 3
---

```{r setup, message=FALSE, warning=FALSE}
#libraries
library(readxl)
library(dplyr)
library(ggplot2)
library(readxl)
library(survival)
library(survminer)
library(tableone)
library(mice)
library(plotly)
library(table1)
library(tidyr)
library(readr)
library(dplyr)
library(table1)
library(survival)
library(survminer)
library(WinRatio) 
library(BuyseTest)
library(msm)
library(cmprsk)
library(dcurves)
library(tidyverse)
library(gtsummary)

```

```{r}
#load dataset
PCA <- read_excel("PCA_Clinical_Annotation.xls")
head(PCA)
```

```{r}
# Clean the data to improve readability
clean_df <- PCA %>%
  filter(Type == "PRIMARY") %>%
  mutate(
    
    # ID
    id = `Sample ID`,
    
    # Overall Survival
    os_time   = as.numeric(SurvTime),
    os_status = ifelse(Event == "NO", 0, 1),
    
    # BCR
    bcr_time   = as.numeric(BCR_FreeTime),
    bcr_status = ifelse(BCR_Event == "BCR_Algorithm", 1, 0),
    
    # Metastasis
    met_status = ifelse(MetsEvent == "NO", 0, 1),
    
    # Baseline variables
    Age = as.numeric(DxAge),
    PSA = as.numeric(gsub("[^0-9.]", "", PreTxPSA)),
    
    Race = factor(Race),
    ClinT_Stage = factor(ClinT_Stage) %>%
      recode("T1C" = "T1",
             "T2A" = "T2", "T2B" = "T2","T2C" = "T2",
             "T3A" = "T3", "T3B" = "T3"),
    PathStage = factor(PathStage) %>%
      recode("T2A" = "T2",
             "T2B" = "T3","T2C" = "T2",
             "T3A" = "T3","T3B"	= "T3", "T3C" = "T3"),
    
    # Nomogram
    NomoPred_SVI = as.numeric(`Nomogram NomoPred_SVI`)
    
  ) %>%
  select(
    id,
    Age, PSA,
    Race, ClinT_Stage, PathStage, NomoPred_SVI,
    bcr_time, bcr_status,
    met_status,
    os_time, os_status
  )

clean_df$NomoPred_SVI[is.na(clean_df$NomoPred_SVI)] <- median(clean_df$NomoPred_SVI, na.rm = TRUE)
```

```{r}
names(clean_df)
dim(clean_df)
head(clean_df)
```

## Numeric summary
```{r}
numeric_summary <- clean_df %>%
  summarise(
    mean_OS    = mean(os_time, na.rm = TRUE),
    sd_OS      = sd(os_time, na.rm = TRUE),
    median_OS  = median(os_time, na.rm = TRUE),
    min_OS     = min(os_time, na.rm = TRUE),
    max_OS     = max(os_time, na.rm = TRUE),
    
    mean_BCR   = mean(bcr_time, na.rm = TRUE),
    sd_BCR     = sd(bcr_time, na.rm = TRUE),
    median_BCR = median(bcr_time, na.rm = TRUE),
    min_BCR    = min(bcr_time, na.rm = TRUE),
    max_BCR    = max(bcr_time, na.rm = TRUE),
    
    mean_Age   = mean(Age, na.rm = TRUE),
    sd_Age     = sd(Age, na.rm = TRUE),
    mean_PSA   = mean(PSA, na.rm = TRUE),
    sd_PSA     = sd(PSA, na.rm = TRUE)
  )

numeric_summary
```

## Summary statistics for categorical variables
```{r}
label(clean_df$Race)        <- "Race"
label(clean_df$ClinT_Stage) <- "Clinical T Stage"
label(clean_df$PathStage)   <- "Pathological Stage"

table1(~ Race + ClinT_Stage + PathStage, data = clean_df)
```

```{r}
clean_df_plot <- clean_df %>%
  mutate(met_status = factor (met_status,
                              levels = c(0,1),
                              labels = c("No Metastasis", "Metastasis Event")))
met_plot <- ggplot(clean_df_plot, aes(x = ClinT_Stage, fill = as.factor(met_status))) +
  geom_bar(position = "dodge") +
  labs(
    title = "Metastasis Events by Clinical T Stage",
    x = "Clinical T Stage",
    y = "Count",
    fill = "Metastasis"
  ) +
  scale_fill_manual(
    values = c("No Metastasis" = "steelblue", "Metastasis Event" = "tomato"),
    ) +
  theme_minimal()

ggplotly(met_plot)
```

```{r}
met_plot_path <- ggplot(clean_df_plot, aes(x = PathStage, fill = as.factor(met_status))) +
  geom_bar(position = "dodge") +
  labs(
    title = "Metastasis Events by Pathological Stage",
    x = "Pathological Stage",
    y = "Count",
    fill = "Metastasis"
  ) +
  scale_fill_manual(
    values = c("No Metastasis" = "steelblue", "Metastasis Event" = "tomato"),
    ) +
  theme_minimal()

ggplotly(met_plot_path)
```

```{r}
event_count <- clean_df %>%
  summarise(
    BCR_Events = sum(bcr_status == 1, na.rm = TRUE),
    MET_Events = sum(met_status == 1, na.rm = TRUE),
    OS_Events  = sum(os_status == 1, na.rm = TRUE)
  )
event_count
```

```{r}
event_long <- event_count %>%
  pivot_longer(
    cols = c(BCR_Events, MET_Events, OS_Events),
    names_to = "Endpoint",
    values_to = "Events"
  )

plot_events <- ggplot(event_long, aes(x = Endpoint, y = Events, fill = Endpoint)) +
  geom_col(position = position_dodge(width = 0.7)) +
  labs(
    title = "BCR, MET and OS: Event Counts",
    x = "Endpoint",
    y = "No. of events",
    fill = "Endpoint"
  ) +
  theme_minimal()

ggplotly(plot_events)
```

## Baseline variables
```{r}
vars <- c("Age", "PSA", "Race", "ClinT_Stage", "PathStage",
          "os_status", "bcr_status", "met_status")
factorVars <- c("Race", "ClinT_Stage", "PathStage")

tab1 <- CreateTableOne(
  vars = vars,
  strata = "ClinT_Stage",
  data = clean_df,
  factorVars = factorVars,
  test = TRUE
)

tab1
```

## Composite Outcome
```{r}
clean_df <- clean_df %>%
  mutate(
    met_time = ifelse(met_status ==1 , pmin(os_time, bcr_time, na.rm = TRUE),
                      pmin(os_time, bcr_time, na.rm = TRUE)),
    comp_status = pmax(os_status, bcr_status, met_status),
    comp_time = pmin(os_time, bcr_time, met_time, na.rm = TRUE)
  )

table1(~ comp_status + comp_time + met_status + met_time, data = clean_df)
```

## Binary outcome
```{r}
clean_df <- clean_df %>%
  mutate(
    binary_os   = factor(os_status, levels = c(0, 1), labels = c("No Event", "Event")),
    binary_bcr  = factor(bcr_status, levels = c(0, 1), labels = c("No Event", "Event")),
    binary_met  = factor(met_status, levels = c(0, 1), labels = c("No Event", "Event")),
    binary_comp = factor(comp_status, levels = c(0, 1), labels = c("No Event", "Event"))
  )

table(clean_df$binary_os)
table(clean_df$binary_bcr)
table(clean_df$binary_met)
table(clean_df$binary_comp)
```

## Logistic Regression
```{r, warning=FALSE}

clean_df$ClinT_Stage <- relevel(clean_df$ClinT_Stage, ref = "T1")

log_os <- glm(os_status ~ Age + PSA + ClinT_Stage,
              family = binomial, data = clean_df)

log_bcr <- glm(bcr_status ~ Age + PSA + ClinT_Stage,
               family = binomial, data = clean_df)

log_met <- glm(met_status ~ Age + PSA + ClinT_Stage,
               family = binomial, data = clean_df)

log_comp <- glm(comp_status ~ Age + PSA + ClinT_Stage,
                family = binomial, data = clean_df)

tidy_logistic <- function(fit, title){
  broom::tidy(fit, exponentiate = TRUE, conf.int = TRUE) |>
    mutate(
      OR_CI = sprintf("%.2f (%.2f-%.2f)", estimate, conf.low, conf.high),
      p = signif(p.value, 3)
    ) |>
    select(term, OR_CI, p) |>
    rename(Variable = term, `OR (95% CI)` = OR_CI, `p-value` = p) |>
    (\(df){
      cat(paste0("<b>", title, "</b>"))
      knitr::kable(df, format = "html", escape = FALSE) |>
        kableExtra::kable_styling(full_width = TRUE, font_size = 18)
    })()
}

tidy_logistic(log_os, "Logistic - OS Event")
cat("<br>")
tidy_logistic(log_bcr, "Logistic - BCR Event")
cat("<br>")
tidy_logistic(log_met, "Logistic - MET Event")
cat("<br>")
tidy_logistic(log_comp, "Logistic - Composite Event")
```
## Cumulative incidence
```{r}


fit <- cuminc(ftime = clean_df$comp_time, fstatus = clean_df$comp_status, 
              group = clean_df$ClinT_Stage)

ggcompetingrisks(fit) + 
  labs(title = "Progression Cascade by T-Stage", 
       x = "Time (months)", y = "Cumulative Incidence") 
```

## Kaplan-Meier plots
```{r}
clean_df <- clean_df %>%
  mutate(
    bcr_time = ifelse(is.na(bcr_time), os_time, bcr_time),
    met_time = ifelse(is.na(met_time), os_time, met_time),
    comp_time = pmin(os_time, bcr_time, met_time, na.rm = TRUE),
    across(c(bcr_time, met_time, comp_time), ~pmax(., 0.001))
  )

# BCR Kaplan-Meier plot

km_bcr <- survfit(Surv(bcr_time, bcr_status) ~ ClinT_Stage, data = clean_df)
ggsurvplot(km_bcr,
           data = clean_df,
           pval = TRUE,
           conf.int = TRUE,
           palette = c("blue", "green", "red"),
           title = "BCR-Free Survival by Clinical T-Stage",
           xlab = "Time (months)", 
           ylab = "BCR-Free Probability",
           legend.title = "ClinT_Stage",
           legend.labs = c("T1", "T2", "T3"))

# Metastasis Kaplan-Meier plot  

km_met <- survfit(Surv(met_time, met_status) ~ ClinT_Stage, data = clean_df)

ggsurvplot(km_met, data = clean_df, pval = TRUE, conf.int = TRUE,
           palette = c("blue", "green","red"),
           title = "Metastasis-Free Survival by T-Stage")

# Composite Kaplan-Meier plot

km_comp <- survfit(Surv(comp_time, comp_status) ~ ClinT_Stage, data = clean_df)

ggsurvplot(km_comp, data = clean_df, pval = TRUE, conf.int = TRUE,
           title = "Event-Free Survival by T-Stage")
```

```{r}

df_binary <- clean_df %>%
  mutate(
    binary_os   = factor(os_status, levels = c(0, 1), labels = c("No Event", "Event")),
    binary_bcr  = factor(bcr_status, levels = c(0, 1), labels = c("No Event", "Event")),
    binary_met  = factor(met_status, levels = c(0, 1), labels = c("No Event", "Event")),
    binary_comp = factor(comp_status, levels = c(0, 1), labels = c("No Event", "Event"))
  )

# summarize data
df_binary %>%
  select(-id) %>%
  tbl_summary(type = all_dichotomous() ~ "categorical")


```

## Decision Curve Analysis
```{r}

mod_os <- glm(os_status ~ Age + PSA + ClinT_Stage,
              family = binomial, data = df_binary)

df_binary$pred_os<- predict(mod_os, newdata = df_binary, type = "response")

dca_model_os <- dca(
  os_status ~ pred_os,
  data = df_binary
)
plot(dca_model_os)


mod_bcr <- glm(bcr_status ~ Age + PSA + ClinT_Stage,
               family = binomial, data = df_binary)

df_binary$pred_bcr<- predict(mod_bcr, newdata = df_binary, type = "response")

dca_model_bcr <- dca(
  bcr_status ~ pred_bcr,
  data = df_binary
)


mod_met <- glm(met_status ~ Age + PSA + ClinT_Stage,
               family = binomial, data = df_binary)

df_binary$pred_met<- predict(mod_met, newdata = df_binary, type = "response")

dca_model_met <- dca(
  met_status ~ pred_met,
  data = df_binary
)


mod_comp <- glm(comp_status ~ Age + PSA + ClinT_Stage,
                family = binomial, data = df_binary)

df_binary$pred_comp<- predict(mod_comp, newdata = df_binary, type = "response")

dca_model_comp <- dca(
  comp_status ~ pred_comp,
  data = df_binary
)

dca_compare <- dca(
  os_status ~ pred_os + pred_comp + pred_met,
  data = df_binary
)

plot(dca_compare)

```

```{r}
summary(df_binary$PSA)
any(is.na(df_binary$PSA))

```


## COX model and PH test
```{r}

# COX Model 

clean_df <- clean_df %>%
  mutate(
    bcr_time = ifelse(is.na(bcr_time), os_time, bcr_time),
    met_time = ifelse(is.na(met_time), os_time, met_time),
    comp_time = pmin(os_time, bcr_time, met_time, na.rm = TRUE),
    across(c(bcr_time, met_time, comp_time), ~pmax(., 0.001))
  )

cox_os <- coxph(Surv(os_time, os_status) ~ Age + PSA + ClinT_Stage, data = clean_df, ties = "efron")

cox_met <- coxph(Surv(met_time, met_status) ~ Age + PSA + ClinT_Stage, data = clean_df, ties = "efron")

cox_bcr <- coxph(Surv(bcr_time, bcr_status) ~ Age + PSA + ClinT_Stage, data = clean_df, ties = "efron")

cox_comp <- coxph(Surv(comp_time, comp_status) ~ Age + PSA + ClinT_Stage, data = clean_df, ties = "efron")

tidy_cox <- function(fit, title){
  broom::tidy(fit, exponentiate = TRUE, conf.int = TRUE) |>
    mutate(
      HR_CI = sprintf("%.2f (%.2f–%.2f)", estimate, conf.low, conf.high),
      p = signif(p.value, 3)
    ) |>
    select(term, HR_CI, p) |>
    rename(Variable = term, `HR (95% CI)` = HR_CI, `p-value` = p) |>
    (\(df){
      cat(paste0("<b>", title, "</b>"))
      knitr::kable(df, format="html", escape=TRUE) |>
        kableExtra::kable_styling(full_width=TRUE, font_size=18)
    })()
}

tidy_cox(cox_os,  "Cox model — Overall Survival")


tidy_cox(cox_met,  "Cox model — Metastatic Survival")


tidy_cox(cox_bcr,  "Cox model — Biochemical Recurrence (BCR)")

tidy_cox(cox_comp,  "Cox model — Composite Outcome")

ph_test_met <- cox.zph(cox_met)
ph_test_bcr <- cox.zph(cox_bcr)
ph_test_comp <- cox.zph(cox_comp)
ph_test_met
ph_test_bcr
ph_test_comp
plot(ph_test_bcr)
plot(ph_test_comp)
plot(ph_test_met)
```



## Multi-State Model
```{r}
# Preparing the dataset -  Censoring, ordering the events, ensuring positive time, log transform PSA

clean_df <- clean_df %>%
  mutate(
    bcr_time = ifelse(is.na(bcr_time), os_time, bcr_time),
    met_time = ifelse(is.na(met_time), os_time, met_time),
    
    bcr_time = pmax(bcr_time, 0.001),
    met_time = pmax(met_time, 0.001),
    os_time  = pmax(os_time, 0.001),

   
    log_PSA = log(PSA + 1)
  )


ms_data <- tmerge(
  data1 = clean_df,
  data2 = clean_df,
  id = id,
  tstart = 0,
  tstop = os_time
)

ms_data <- tmerge(ms_data, clean_df, id = id,
                  bcr = event(bcr_time, bcr_status),
                  met = event(met_time, met_status),
                  death = event(os_time, os_status))


# Defining transitions

ms_data <- ms_data %>%
  mutate(
    trans = case_when(
     bcr == 1 ~ "0->1",

      met == 1 & (bcr_time >= met_time | is.na(bcr_time)) ~ "0->2",

      death == 1 &
        (bcr_time > os_time)& (met_time > os_time) ~ "0->3",

      # After BCR (state 1)
      met == 1 & bcr_time < met_time ~ "1->2",

      death == 1 &
        bcr_time < os_time &
        (met_time > os_time | is.na(met_time)) ~ "1->3",

      # After metastasis (state 2)
      death == 1 & met_time < os_time ~ "2->3",

      TRUE ~ NA_character_
    )
  )


#Fitting MSM
ms_data$trans <- factor(ms_data$trans,
                        levels = c("0->1","0->2","0->3",
                                   "1->2","1->3","2->3"))

ms_data <- ms_data %>%
  mutate(event = ifelse(!is.na(trans), 1, 0))

cox_msm <- coxph(
  Surv(tstart, tstop, event) ~ Age + log_PSA + ClinT_Stage + strata(trans),
  data = ms_data
)

summary(cox_msm)

cox_msm_mod2 <- coxph(
  Surv(tstart, tstop, event) ~
    Age +
    log_PSA +
    ClinT_Stage*trans,
  data = ms_data
)

summary(cox_msm_mod2)

#PH assumption check

ph_msm <- cox.zph(cox_msm)
ph_msm2 <- cox.zph(cox_msm_mod2)

# Visualisation 

ggcoxzph(ph_msm)

ggcoxzph(ph_msm2)



```